
#ifndef _AANET_H
#define _AANET_H

extern const unsigned short *A_tyhja[];
extern const unsigned short *A_Mvoitto[];
extern const unsigned short *A_Mtuplaus[];
extern const unsigned short *A_Mtsajaja[];
extern const unsigned short *A_Mkoputus[];
extern const unsigned short *A_Mkonkka[];

extern const unsigned short *A_Aliuku[];
extern const unsigned short *A_Asekoita[];
extern const unsigned short *A_Apudotus[];
extern const unsigned short *A_Akaantyy[];
extern const unsigned short *A_Avalinta[];
extern const unsigned short *A_Aasettuu[];
extern const unsigned short *A_Amaksu[];
extern const unsigned short *A_Aperkele[];
extern const unsigned short *A_Aaloita[];
extern const unsigned short *A_Apanos1[];
extern const unsigned short *A_Apanos2[];
extern const unsigned short *A_Apanos3[];
extern const unsigned short *A_Apanos4[];
extern const unsigned short *A_Apanos5[];

#endif
