
#ifndef _KUVAT_H
#define _KUVAT_H

extern const unsigned char G_selka[];
extern const unsigned char G_font[];
extern const unsigned char G_vfont[];

extern const unsigned char G_spata[];
extern const unsigned char G_shertta[];
extern const unsigned char G_sruutu[];
extern const unsigned char G_sristi[];
extern const unsigned char G_spata_U[];
extern const unsigned char G_shertta_U[];
extern const unsigned char G_sruutu_U[];
extern const unsigned char G_sristi_U[];

extern const unsigned char G_ppata[];
extern const unsigned char G_phertta[];
extern const unsigned char G_pruutu[];
extern const unsigned char G_pristi[];
extern const unsigned char G_ppata_U[];
extern const unsigned char G_phertta_U[];
extern const unsigned char G_pruutu_U[];
extern const unsigned char G_pristi_U[];

extern const unsigned char G_arvoA[];
extern const unsigned char G_arvoK[];
extern const unsigned char G_arvoQ[];
extern const unsigned char G_arvoJ[];
extern const unsigned char G_arvoT[];
extern const unsigned char G_arvo9[];
extern const unsigned char G_arvo8[];
extern const unsigned char G_arvo7[];
extern const unsigned char G_arvo6[];
extern const unsigned char G_arvo5[];
extern const unsigned char G_arvo4[];
extern const unsigned char G_arvo3[];
extern const unsigned char G_arvo2[];

extern const unsigned char G_arvoA_U[];
extern const unsigned char G_arvoK_U[];
extern const unsigned char G_arvoQ_U[];
extern const unsigned char G_arvoJ_U[];
extern const unsigned char G_arvoT_U[];
extern const unsigned char G_arvo9_U[];
extern const unsigned char G_arvo8_U[];
extern const unsigned char G_arvo7_U[];
extern const unsigned char G_arvo6_U[];
extern const unsigned char G_arvo5_U[];
extern const unsigned char G_arvo4_U[];
extern const unsigned char G_arvo3_U[];
extern const unsigned char G_arvo2_U[];

extern const unsigned char G_arvojok[];

extern const unsigned char G_lantti[];
extern const unsigned char G_lantti_M[];

extern const unsigned char G_tulosv[];
extern const unsigned char G_tulosv_M[];
extern const unsigned char G_tuloso[];
extern const unsigned char G_tuloso_M[];

extern const unsigned char G_jatka[];
extern const unsigned char G_akka[];
extern const unsigned char G_kurko[];
extern const unsigned char G_jokeri[];

#endif
